site_name: GSEE
site_description: Global Solar Energy Estimator
site_url: https://gsee.readthedocs.io/

theme:
    name: material
    logo: ninja.png
    favicon: favicon.ico
    features:
        - navigation.indexes
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - content.code.copy

repo_name: renewables-ninja/gsee
repo_url: https://github.com/renewables-ninja/gsee/
edit_uri: ""

nav:
    - Introduction:
        - index.md
        - Migrating from v0.3: migrating.md
    - Running:
        - running/index.md
        - PV models: running/pv-models.md
        - Multi-site simulations: running/multi-site.md
        - Legacy options: running/legacy.md
    - Diffuse fraction: diffuse-fraction.md
    - Climate data interface: climatedata-interface.md
    - Development: development.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - 'stylesheets/extra.css'
