name: Tests

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.10.0
        with:
          cache: true
      - run: pixi run lint
      - run: pixi run format-check

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.10.0
        with:
          cache: true
      - run: pixi run docs-build

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.10.0
        with:
          cache: true
      - run: pixi run test
        if: matrix.os != 'ubuntu-latest'
      - run: pixi run test-cov
        if: matrix.os == 'ubuntu-latest'
      - uses: codecov/codecov-action@v5
        if: matrix.os == 'ubuntu-latest'
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
